version: '3.8'
services:
  postgres:
    image: postgres
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  migrate:
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ./db/migrations:/db/migrations
    environment:
      DB_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
    command: 
      - "-path=/db/migrations"
      - "-database=$$DB_URL"
      - "up"

volumes:
  pg_data:

# for migrations, to run up:
# docker-compose run migrate up

# for migrations, to run down:
# docker-compose run migrate down